name: Build and deploy Docker container to Azure Web App

on:
  push:
    branches:
      - mik/azure-app-service-deployment
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: patoekipa-portfolio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./nextjs
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/patoekipa-portfolio:${{ github.sha }}
          build-args: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            COSMOS_DB_ENDPOINT=${{ secrets.COSMOS_DB_ENDPOINT }}
            COSMOS_DB_KEY=${{ secrets.COSMOS_DB_KEY }}
            COSMOS_DB_DATABASE_NAME=${{ secrets.COSMOS_DB_DATABASE_NAME }}
            COSMOS_DB_CONTAINER_NAME=${{ secrets.COSMOS_DB_CONTAINER_NAME }}
            NODE_ENV=production
            NEXT_TELEMETRY_DISABLED=1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          images: ${{ secrets.DOCKER_USERNAME }}/patoekipa-portfolio:${{ github.sha }} 